name: ParseToken_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.OAuth.ParseToken/**'
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/build_main.yml@main
    with:
      workdir: Frends.OAuth.ParseToken
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}